### ISSUE TITLE
Help with usage

### ISSUE THREAD

**Issue by rogdevil** [eosdac/ual-wax#15]
i am getting the following error when i try to use ual-wax in my dummy app
![image](https://user-images.githubusercontent.com/43280610/129773896-aa507056-353d-401b-9e9f-4e3ca582281b.png)

`
import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';
import reportWebVitals from './reportWebVitals';
import { Anchor } from 'ual-anchor'
import { Wax } from '@eosdacio/ual-wax'
import { UALProvider, withUAL } from 'ual-reactjs-renderer'

const eos = {
  chainId: '1064487b3cd1a897ce03ae5b6a865651747e2e152090f99c1d19d44e01aea5a4',
  rpcEndpoints: [{
    protocol: 'https',
    host: 'api.waxsweden.org',
    port: '443',
  }]
}

const AppWithUAL = withUAL(App)

const anchor = new Anchor([eos], {appName: "aryan"})
const wax = new Wax([eos])

ReactDOM.render(
  <React.StrictMode>
    <UALProvider chains={[eos]} authenticators={[anchor, wax]} appName={'aryan'} >
      <AppWithUAL />
    </UALProvider>
  </React.StrictMode>,
  document.getElementById('root')
);
`
here is my index.js

**Comment by kjg** [comment]
There is an issue with the npm released version of V1.5.0 (see #13). You can try downgrading to 1.4.x or linking directly to GitHub version until they fix the issue or publish a new version.

**Comment by rogdevil** [comment]
okey dokey ..... thanks for you reply
